export const USER = {
    SET_ADDRESS: 'USER_SET_ADDRESS',
    SET_NAME: 'USER_SET_NAME',
    SET_DESCRIPTION: 'USER_SET_DESCRIPTION',
    SET_OWNER_IMAGES: 'USER_SET_OWNER_IMAGES',
    SET_AUTHOR_IMAGES: 'USER_SET_AUTHOR_IMAGES'
};

export const ALERT = {
    SET_MESSAGE: 'ALERT_SET_MESSAGE',
    CLEAR_MESSAGE: 'ALERT_CLEAR_MESSAGE'
};

export const LOADING = {
    TURN_ON: 'LOADING_TURN_ON',
    TURN_OFF: 'LOADING_TURN_OFF',
}

export const IMAGE = {
    SET_HASH: 'IMAGE_SET_HASH',
    SET_IS_DUPLICATE: 'IMAGE_SET_IS_DUPLICATE',
    CLEAR_DATA: 'IMAGE_CLEAR_DATA'
}


